# Generated by Django 5.0.4 on 2024-05-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_stock_producto_stock_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacion_categoria', models.CharField(choices=[('color', 'color'), ('procedencia', 'procedencia')], max_length=100)),
                ('valor_variacion', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
    ]
