# Generated by Django 5.0.4 on 2024-05-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_variaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variaciones',
            name='variacion_categoria',
            field=models.CharField(choices=[('color', 'color'), ('marca', 'marca')], max_length=100),
        ),
    ]
