# Generated by Django 5.0.4 on 2024-05-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('tienda', '0004_alter_variaciones_variacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variaciones',
            field=models.ManyToManyField(blank=True, to='tienda.variaciones'),
        ),
    ]
