# Generated by Django 5.0.4 on 2024-06-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='confirmado',
            field=models.BooleanField(default=True),
        ),
    ]
