# Generated by Django 5.0.4 on 2024-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
