# Generated by Django 5.0.4 on 2024-05-28 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_cuenta_is_client_cuenta_is_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_1', models.CharField(blank=True, max_length=100)),
                ('direccion_2', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=20)),
                ('municipio', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(blank=True, max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
