# Generated by Django 5.0.4 on 2024-05-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='is_staff',
        ),
    ]
