# Generated by Django 5.0.4 on 2024-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_remove_cuenta_is_admin_remove_cuenta_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
