# Generated by Django 5.0.4 on 2024-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_cuenta_is_admin_cuenta_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='perfilusuario/'),
        ),
    ]
